export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";

export const MOVIES_RANDOM_REQUEST = "MOVIES_RANDOM_REQUEST"
export const MOVIES_RANDOM_SUCCESS = "MOVIES_RANDOM_SUCCESS"
export const MOVIES_RANDOM_FAIL = "MOVIES_RANDOM_FAIL"

export const MOVIES_DETAIL_REQUEST = "MOVIES_DETAIL_REQUEST";
export const MOVIES_DETAIL_SUCCESS = "MOVIES_DETAIL_SUCCESS";
export const MOVIES_DETAIL_FAIL = "MOVIES_DETAIL_FAIL";
export const MOVIES_DETAIL_RESET = "MOVIES_DETAIL_RESET";

export const MOVIES_TOP_RATED_REQUEST = "MOVIES_TOP_RATED_REQUEST";
export const MOVIES_TOP_RATED_SUCCESS = "MOVIES_TOP_RATED_SUCCESS";
export const MOVIES_TOP_RATED_FAIL = "MOVIES_TOP_RATED_FAIL";


export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";
